### ISSUE TITLE
How to deal with large datasets - gitignore?

### ISSUE THREAD

**Issue by brettmelbourne** [EBIO6100Spring2020/Data-sandbox#9]
We're already running across a problem, which is data too big for GitHub. As @mbjoseph mentioned, a simple solution is to script the data download and commit the code but don't commit the data file. Include the data file in .gitignore so it's ignored. There are at least two ways we could do this 1) put all the big data in their own directory (e.g. data_big) and then ignore the entire directory, 2) mix big and small data but gitignore individual files (you can even have a separate .gitignore file in the data directory).
https://help.github.com/en/github/using-git/ignoring-files
Perhaps (2) to keep the directory structure simpler?

**Comment by mbjoseph** [comment]
I like option 2 (e.g., the `data_raw`) directory, which contains raw data regardless of size. 

We could use pattern matching in a `.gitignore` file to ignore files that end with certain extensions, rather than having an ignore rule for each individual file. So for example, we could create a file `data_raw/.gitignore` that will ignore any CSV or TIF files: 

```
# ignore files matching the following patterns:
*.csv
*.tif
```

**Comment by scelmendorf** [comment]
I think there *might* be some smallish data_raw .csvs that we do want to push to git, e.g. .csv of species of interest or something (also there is niwot flux data which is apparently suspect so not on EDI, but in a pinch I could share it in the data_raw; there might be other stuff like that as well). So I'd advocate for ignoring individual files or subdirectories under data_raw (this is @WynneMoss did today - I think?), rather than all csvs. But also, I don't stongly care so if others love option 2 then go for it.

**Comment by mbjoseph** [comment]
Good point @scelmendorf! 

We also have the option to ignore subdirectories within the `data_raw` directory, e.g., if somebody needs to download a whole bunch of related files.

**Comment by brettmelbourne** [comment]
OK, I set up option (2) to ignore individual files within data directories. I set up .gitignore files with sensible rules in the base repo directory (for RStudio and operating system cruft etc), and one in each of the data directories for ignoring large data files (no rules added yet; please add as need arises).
